name: pa11y-accessibility-check
on:
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Install Chrome
        run:
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install Pa11y
        run: |
          npm install -g pa11y
      - run: npm run dev & npx wait-on http://localhost:3000 &
      - name: Run pa11y
        run: pa11y http://localhost:3000 --chrome-launcher --no-sandbox
