name: pa11y-accessibility-check
on:
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Install Pa11y, http-server, and Chromium for Pa11y
        run: |
          npm install -g pa11y http-server
      # - run: http-server ./dist --port 3000 &
      - run: npm run dev & npx wait-on http://localhost:3000 &
      - name: Run pa11y
        run: pa11y http://localhost:3000 || exit 0
